config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

   root 'reports#index'

    get 'get_departments' => 'home#get_list_departments'
    get 'get_departments_list' => 'reports#get_departments_list'
    get 'get_courses_list' => 'reports#get_courses_list'
    get '/search_reports' => 'reports#search'
    post '/submit_review' => 'reports#submit_review'

  resources :reports do
    member do
      get 'submit_report'
    end
  end

end

app/models/report.rb
class Report < ActiveRecord::Base
belongs_to :college
belongs_to :department
belongs_to :course
has_attached_file :avatar#, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
#validates_attachment_content_type :avatar, content_type: ["image/jpeg", "image/gif", "image/png"]
do_not_validate_attachment_file_type :avatar
has_many :goals
accepts_nested_attributes_for :goals,allow_destroy: true

#serialize :learning_goals, :strategic_plan

def self.search(params)
  #if params.any?{|k,v| v.empty?}
  #	self.all
  #else
  params[:college_id] = params[:college_id].present? ? params[:college_id] : nil
  params[:deparment_id] = params[:department_id].present? ? params[:department_id] : nil
  params[:course_id] = params[:course_id].present? ? params[:course_id] : nil
  params[:year] = params[:year].present? ? params[:year] : nil
  
  if params[:role] == 'Director'
    self.where('course_id =? AND extract(year from created_at) = ?',params[:course_id],params[:year])  
  else
  	self.where('college_id = ? AND department_id = ? AND course_id =? AND extract(year from created_at) = ?',params[:college_id], params[:deparment_id],params[:course_id],params[:year])
  end
end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy, :submit_report, :submit_review]
  before_action :authenticate_user!
  before_filter :require_permission, only: [:new,:create]

  # GET /reports
  # GET /reports.json
  def index
    if current_user.role_type == 'Advisor'
      @reports = Report.where('user_id=?',current_user.id).order('updated_at DESC')
    elsif current_user.role_type == 'Director'
      @reports = Report.where('college_id =? AND department_id=? AND status IN(?)',current_user.college_id,current_user.department_id,['Completed','Submitted']).order('updated_at DESC')
    else
      @reports = Report.all.order('updated_at DESC')
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
   @departments = @report.college_id.present? ? Department.where('college_id=?',@report.college_id) : []
   @courses = @report.department_id.present? ? Course.where('department_id=?',@report.department_id) : []
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)
    #@reports_cols = params[:report].any?{|k,v| v.nil?}
    #@goals_cols = params["report"]["goals_attributes"].present? ? params["report"]["goals_attributes"].values.first.any?{|k,v| v.empty?} : false
    
    #@report.status = @reports_cols && @goals_cols ? 'Completed' : 'Incomplete'
    @report.user_id = current_user.id
    @report.end_period = params[:report][:end_period]
    #["report"]["goals_attributes"].values.first["learning_goals"] = ["report"]["goals_attributes"].values.first["learning_goals"].join(",")
    
    respond_to do |format|
      if @report.save
      	update_status(@report)
        format.html { redirect_to reports_url, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      #@reports_cols = params[:report].any?{|k,v| v.nil?}
    #@goals_cols = params["report"]["goals_attributes"].present? ? params["report"]["goals_attributes"].values.first.any?{|k,v| v.empty?} : false
    
    #@report.status = @reports_cols && @goals_cols ? 'Completed' : 'Incomplete'
      if @report.update(report_params)
      	update_status(@report)
        format.html { redirect_to reports_url, notice: 'Report was successfully saved.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_status(report)
  	r_status = report.college_id.present? && report.department_id.present? && report.course_id.present? && report.assessment_start_period.present? && report.end_period.present? && report.state_all_slos.present? && report.improvements_on_report_period.present?
    p '@@@@@@'
    p r_status
    if report.goals.present?
      goal = report.goals.first
      g_status = goal.outcome.present? && goal.learning_goals.present? && goal.strategic_plan.present? && goal.measure_type.present? && goal.performance_benchmark.present? && goal.data_results.present? && goal.data_analysis.present? && goal.recommendations.present? && goal.met_details.present?
    end
     p g_status
      g_status = report.goals.present? ? g_status : false
      p g_status
      @status = r_status && g_status ? 'Completed' : 'Incomplete'
      report.update_attributes(:status => @status)
  end

  def get_departments_list
  @departments = Department.where('college_id=?',params[:college_id])
  @department_id = @departments.first.id
  @courses = Course.where('department_id=?',@department_id)
  end

  def get_courses_list
    @courses = Course.where('department_id=?',params[:department_id])
  end

  def submit_report
   @report.update_attributes(:status=>'Submitted')
   respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully Submitted.' }
      format.json { head :no_content }
    end
  end

  def search
  	@reports = Report.search(params[:report])
  end

  def submit_review
  	@report.update_attributes(:comments => params[:report][:comments], :score => params[:report][:score])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:college_id, :department_id, :course_id, :assessment_start_period, :end_period, :submitted_date, :status, :state_all_slos, :focus_on_slos, :improvements_on_report_period, :user_id,:comments,:score,:avatar,
      	goals_attributes: [:id, :outcome,:learning_goals, :strategic_plan,:measure_type,:performance_benchmark,:data_results,:data_analysis,:recommendations,:met_details,:report_id,:_destroy])
    end

	def require_permission
	  if user_role != 'Advisor'
	    respond_to do |format|
	      format.html { redirect_to reports_url, notice: "You can't create reports." }
	    end
	  else
	   	return true
	  end
	end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_filter.html.erb
<% if user_role == 'Director' %>
 <%= form_for(:report, :url => '/search_reports', :method => 'get', :remote => true,:html => {:class=>"form-horizontal table-bordered"}) do |f| %>
<div class="form-group">
      <span class="col-md-1 control-label"></span>
      <div class="col-md-6">
        <div class="form-group row">
          
     <label class="col-md-2 control-label">Courses</label>
    <div class="col-md-4">
          <%= collection_select(:report, :course_id, Course.where('department_id=?',current_user.department_id), :id, :name, {:prompt => 'Select Department First'},:class=>'form-control') %>
    </div>
    <label class="col-md-1 control-label">Year</label>
    <div class="col-md-3">
        <select name="report[year]">
  <option value="2015" selected="selected">2015</option>
  <option value="2016">2016</option>
 <option value="2017">2017</option>
 <option value="2018">2018</option>
 <option value="2019">2019</option>
 <option value="2020">2020</option>
 <option value="2021">2021</option>
</select>
<input type="hidden" name ="report[role]" value="<%= user_role %>">
    </div>
        </div>    
      </div>
      <span class="col-md-1 control-label"><%= f.submit 'Search', :class => 'btn btn-primary btn-small' %></span>
  </div>

  <% end %>

<% else %>
<%= form_for(:report, :url => '/search_reports', :method => 'get', :remote => true,:html => {:class=>"form-horizontal table-bordered"}) do |f| %>
<div class="form-group">
      <span class="col-md-1 control-label"></span>
      <div class="col-md-8">
        <div class="form-group row">
          <label class="col-md-1 control-label">Colleges</label>
          <div class="col-md-2">
            <%= collection_select(:report, :college_id, College.all, :id, :name, {:prompt => 'Select'},:class=>'form-control') %>
          </div>
    <label class="col-md-2 control-label">Departments</label>
    <div class="col-md-3">
      
        <%= collection_select(:report, :department_id, [], :id, :name, {:prompt => 'Please Select College First'},:class=>'form-control') %>
     
    </div>
     <label class="col-md-1 control-label">Courses</label>
    <div class="col-md-3">
          <%= collection_select(:report, :course_id, [], :id, :name, {:prompt => 'Select Department First'},:class=>'form-control') %>
    </div>
    <label class="col-md-1 control-label">Year</label>
    <div class="col-md-3">
        <select name="report[year]">
  <option value="2015" selected="selected">2015</option>
  <option value="2016">2016</option>
 <option value="2017">2017</option>
 <option value="2018">2018</option>
 <option value="2019">2019</option>
 <option value="2020">2020</option>
 <option value="2021">2021</option>
</select>
<input type="hidden" name ="report[role]" value="<%= user_role %>">
    </div>
        </div>    
      </div>
      <span class="col-md-1 control-label"><%= f.submit 'Search', :class => 'btn btn-primary btn-small' %></span>
  </div>

  <% end %>
  <% end %>
  <script>
  $( "#report_college_id" ).change(function() {
var college = $(this).val();
$.ajax({
        url: '/get_departments_list',
        data: { college_id: college}
    }); 
});

$( "#report_department_id" ).change(function() {
var department = $(this).val();
$.ajax({
        url: '/get_courses_list',
        data: { department_id: department}
    }); 
});

</script>

app/views/reports/_form.html.erb
<br><%= nested_form_for(@report, :html => {:class=>"form-horizontal table-bordered"}) do |f| %><br>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
      <span class="col-md-2 control-label">Metadata</span>
      <div class="col-md-8">
        <div class="form-group row">
          <label class="col-md-1 control-label">Colleges</label>
          <div class="col-md-2">
            <%= f.collection_select :college_id, College.all, :id, :name, {:prompt => 'Select', :selected => @report.college_id},:class=>'form-control' %>
          </div>
    <label class="col-md-2 control-label">Departments</label>
    <div class="col-md-3">
      <% if action_name == 'edit' %>
        <%= f.collection_select :department_id, @departments, :id, :name, {:prompt => 'Select College First', :selected => @report.department_id},:class=>'form-control' %>
      <% else %>
        <%= f.collection_select :department_id, [], :id, :name, {:prompt => 'Please Select College First', :selected => @report.department_id},:class=>'form-control' %>
      <% end %>
    </div>
     <label class="col-md-1 control-label">Courses</label>
    <div class="col-md-3">
      <% if action_name == 'edit' %>
        <% if !@report.course_id.nil? %>
          <%= f.collection_select :course_id, @courses, :id, :name, {:selected => @report.course_id},:class=>'form-control' %>
        <%else %>
          <%= f.collection_select :course_id, [], :id, :name, {:prompt => 'Select Department First'},:class=>'form-control' %>
        <%end %>
      <% else %>
        <%= f.collection_select :course_id, [], :id, :name, {:prompt => 'Select Department First'},:class=>'form-control' %>
      <% end %>
    </div>
          </div>
      </div>
  </div>

  <div class="form-group">
    <span class="col-md-2 control-label">Assessment Period</span>
    <div class="col-md-8">
      <div class="form-group row">
        <label class="col-md-2 control-label">Start</label>
        <div class="col-md-3">
          <%= f.text_field :assessment_start_period, :id => 'start_date',:class=>'form-control' %>  
        </div>
        <label class="col-md-2 control-label">End</label>
        <div class="col-md-3">
          <%= f.text_field :end_period, :id => 'end_date',:class=>'form-control' %> 
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    <span class="col-md-2 control-label">State SLOs/AUOs assessed in 1/2/3 yrs</span>
    <div class="col-md-8">
      <div class="form-group row">
        <div class="col-md-8">
          <%= f.text_area :state_all_slos,:class=>'form-control' %>  
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    <span class="col-md-2 control-label">Actions/Improvements on previou report</span>
    <div class="col-md-8">
      <div class="form-group row">
        <div class="col-md-8">
          <%= f.text_area :improvements_on_report_period,:class=>'form-control' %>  
        </div>
      </div>
    </div>
  </div>

   <div class="form-group">
    <span class="col-md-2 control-label">Evidence Document</span>
    <div class="col-md-8">
      <div class="form-group row">
        <div class="col-md-4">
          <%= f.file_field :avatar,:class=>'form-control' %>  
        </div>
      </div>
    </div>
   </div>

  <%= f.fields_for :goals do |goal| %>
  <div class="form-group">
    <span class="col-md-2 control-label">UNM</span>
    <div class="col-md-8">
      <div class="form-group row">
        <label class="col-md-2 control-label">Learning Goals</label>
        <div class="col-md-3">
          <%#= goal.text_field :learning_goals,:class=>'form-control' %> 
          <%= goal.select(:learning_goals, [['Knowledge', 'Knowledge'],
                                  ['Skills', 'Skills'],
                                  ['Responsibility', 'Responsibility']
                                 ], {:prompt => 'please select'}) %> 
        </div>
        <label class="col-md-2 control-label">Strategic Plan</label>
        <div class="col-md-3">
          <%#= goal.text_field :strategic_plan,:class=>'form-control' %> 
          <%= goal.select(:strategic_plan, [['Students Retention', 'Students Retention'],
                                  ['Persistence', 'Persistence'],
                                  ['Graduation', 'Graduation']
                                 ],{:prompt => 'please select'}) %> 
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    <span class="col-md-2 control-label">Assessment</span>
    <div class="col-md-8">
      <div class="form-group row">
        <label class="col-md-2 control-label">Measures</label>
        <div class="col-md-3">
          <%= goal.text_field :measure_type,:class=>'form-control' %>  
        </div>
        <label class="col-md-2 control-label">Benchmark</label>
        <div class="col-md-3">
          <%= goal.text_field :performance_benchmark,:class=>'form-control' %> 
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    <span class="col-md-2 control-label">Data</span>
    <div class="col-md-8">
      <div class="form-group row">
        <label class="col-md-2 control-label">Analysis</label>
        <div class="col-md-3">
          <%= goal.text_field :data_analysis,:class=>'form-control' %>  
        </div>
        <label class="col-md-2 control-label">Results</label>
        <div class="col-md-3">
          <%= goal.text_field :data_results,:class=>'form-control' %> 
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    <span class="col-md-2 control-label">Learning Outcome</span>
    <div class="col-md-8">
      <div class="form-group row">
        <div class="col-md-8">
          <%= goal.text_area :outcome,:class=>'form-control' %>  
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    <span class="col-md-2 control-label">Recommendations</span>
    <div class="col-md-8">
      <div class="form-group row">
        <div class="col-md-8">
          <%= goal.text_area :recommendations,:class=>'form-control' %>  
        </div>
      </div>
    </div>
  </div>
 
  <div class="form-group">
    <span class="col-md-2 control-label">Meeting Details</span>
    <div class="col-md-8">
      <div class="form-group row">
        <div class="col-md-8">
          <%= goal.text_area :met_details,:class=>'form-control' %>  
        </div>
      </div>
    </div>
  </div>
  <div class="form-group">
    <span class="col-md-2 control-label"></span>
    <div class="col-md-8">
      <div class="form-group row">
      <div class="col-md-8">
       <%= goal.link_to_remove "Remove this goal", :class => 'btn btn-danger btn-sm' %>
       <% end %><br>
       <br><br><%= f.link_to_add "Add a goal", :goals, :class => 'btn btn-primary btn-sm' %>
       </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    <span class="col-md-2 control-label"></span>
    <div class="col-md-8">
      <div class="form-group row">
        <div class="col-md-8">
          <%= f.submit 'Save', :class=>'btn btn-primary' %>  
          <%= link_to 'Submit', submit_report_report_path(:id=>@report.id), data: { confirm: 'Are you sure want to submit to director?' }, :class=>'btn btn-primary' if @report.status=='Completed' && user_role == 'Advisor' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<script>
  $("#start_date").datepicker({
    dateFormat: 'dd-mm-yy'
  });
  $("#end_date").datepicker({
    dateFormat: 'dd-mm-yy'
  });

$( "#report_college_id" ).change(function() {
var college = $(this).val();
$.ajax({
        url: '/get_departments_list',
        data: { college_id: college}
    }); 
});

$( "#report_department_id" ).change(function() {
var department = $(this).val();
$.ajax({
        url: '/get_courses_list',
        data: { department_id: department}
    }); 
});

$( document ).ready(function() {
    $(".footer").hide();
});

</script>

app/views/reports/_reports.html.erb
<% if reports.blank? %>
 <%if user_role =="Advisor"%>
  <center><h4>You don't have any Reports.</h4></center>
 <% elsif user_role =="Director" %>
  <center><h4>You don't have any Reports.</h4></center>
 <%else %>
  <center><h4>No reports were created in system.</h4></center>
 <%end%>
 
<% else %>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <% if ['Director','Admin'].include?(user_role) %>
        <th>User</th>
      <%else%>
        <th>College</th>
        <th>Department</th>
      <%end%>
      <th>Course</th>
      <th>Start period</th>
      <th>End period</th>
      <th>Status</th>
      <% if user_role == 'Admin' %>
       <th>Commented By</th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% reports.each do |report| %>
      <tr>
        
        <% if ['Director','Admin'].include?(user_role) %>
          <td><%= User.where('id=?',report.user_id).first.email %></td>
        <% else %>
          <td><%= report.college_id.present? ? report.college.try(:name) : '--' %></td>
          <td><%= report.department_id.present? ? report.department.try(:name) : '--' %></td>
        <% end %>
        <td><%= report.course_id.present? ? report.course.try(:name) : '--' %></td>
        <td><%= report.assessment_start_period.strftime("%d-%B-%Y") unless report.assessment_start_period.blank?  %></td>
        <td><%= report.end_period.strftime("%d-%B-%Y") unless report.end_period.blank? %></td>
        <td><%= report.status %></td>
         <% if user_role == 'Admin' %>
         <td>
         <% user = User.where('department_id =? AND college_id=?', report.department_id,report.college_id).first %>
         <%= user.present? ? user.try(:email) : 'Not yet commented' %></td>
        <% end %>
        <td><%= link_to 'View', report, :class=>'btn btn-primary btn-xs' %></td>
        <% if report.status != 'Submitted' && user_role == 'Advisor'%>
          <td><%= link_to 'Edit', edit_report_path(report), :class=>'btn btn-primary btn-xs' %></td>
        <% end %>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' }, :class=>'btn btn-danger btn-xs' if report.status != 'Submitted' && user_role == 'Advisor'%></td>
        <% if report.status == 'Completed' && user_role == 'Advisor'%>
          <td>
            <%= link_to 'Submit', submit_report_report_path(:id=>report.id), data: { confirm: 'Are you sure want to submit to director?' }, :class=>'btn btn-primary btn-xs' %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<br><br>
<br>
<% end %>

app/views/reports/edit.html.erb
<h2>Editing Report</h2>

<%= render 'form' %>

app/views/reports/get_courses_list.js.erb
$('#report_course_id').html("<%= escape_javascript options_from_collection_for_select(@courses, :id, :name) %>");

app/views/reports/get_departments_list.js.erb
$('#report_department_id').html("<%= escape_javascript options_from_collection_for_select(@departments, :id, :name) %>");
$('#report_course_id').html("<%= escape_javascript options_from_collection_for_select(@courses, :id, :name) %>");

app/views/reports/index.html.erb
<br>
<%= render :partial => 'filter' %>

<p id="notice"><%= notice %></p>

<%= link_to 'Create New Report', new_report_path, :class=>'btn btn-primary' if user_role == 'Advisor'%><br><br>
<div id="report_list">
  <%= render :partial => 'reports', :locals => {:reports => @reports } %>
</div>

app/views/reports/new.html.erb
<br>
<center><p>Administrative Units Assessment Report Template, 
Record for Assessment of Outcomes,
The University of New Mexico</p></center>

<%= render 'form' %>

app/views/reports/search.js.erb
$('#report_list').html("<%= escape_javascript render(:partial => 'reports', :locals => { :reports => @reports }) %>");

app/views/reports/show.html.erb
     <% if user_role == 'Director' %>
     <%= form_for(@report, :url => '/submit_review', :method => 'post', :remote => true,:html => {:class=>"form-horizontal table-bordered"}) do |f| %>
<div class="form-group">
      <span class="col-md-1 control-label">Review</span>
      <div class="col-md-8">
        <div class="form-group row">
          <label class="col-md-2 control-label">Comments</label>
          <div class="col-md-4">
            <%= f.text_area :comments,:class=>'form-control' %>  
          </div>
          <% if @report.end_period < Time.now %>
           <label class="col-md-1 control-label">Score</label>
          <div class="col-md-2">
            <%= f.text_field :score,:class=>'form-control' %>  
          </div>
          <% end %>
          <input type="hidden" value=<%=@report.id%> name="id">
          <div class="col-md-3">
            <%= f.submit 'Submit review', :class=>'btn btn-primary ' %>  
          </div> 
      </div>
      </div>
      </div>
      <% end %>    
     <% else %>
     <% if @report.status == 'Submitted' || @report.status == 'Completed'  %>
       <div class="form-group" id="review_comment_box">
      <span class="col-md-1 control-label">Review</span>
      <div class="col-md-8">
        <div class="form-group row">
          <label class="col-md-2 control-label">Comments</label>
          <div class="col-md-4">
            <%= @report.comments %>  
          </div>
           <% if user_role != 'Advisor' %>
           <label class="col-md-1 control-label">Score</label>
          <div class="col-md-2">
            <%= @report.score %>  
          </div>
         <% end %>
      </div>
      </div>
      </div>
      <% end %>
     <% end %><br><br><br> 
     <div class="form-group">  
      <div class="col-md-8">
        <div class="form-group row">
          <label class="col-md-1 control-label">College</label>
          <div class="col-md-2">
            <%= @report.college_id ? @report.college.try(:name) : '---'%>
          </div>
    <label class="col-md-2 control-label">Department</label>
    <div class="col-md-3">
     <%= @report.department_id ? @report.department.try(:name) : '---'%>
    </div>
     <label class="col-md-1 control-label">Course</label>
    <div class="col-md-3">
      <%= @report.course_id ? @report.course.try(:name) : '---'%>
    </div>
          </div>
      </div>
  </div>

  <div class="form-group">
    
    <div class="col-md-8">
      <div class="form-group row">
        <label class="col-md-2 control-label">Start</label>
        <div class="col-md-3">
          <%= @report.assessment_start_period.strftime("%d-%B-%Y") unless @report.assessment_start_period.blank? %>  
        </div>
        <label class="col-md-2 control-label">End</label>
        <div class="col-md-3">
          <%= @report.end_period.strftime("%d-%B-%Y") unless @report.end_period.blank? %> 
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    
    <div class="col-md-8">
      <div class="form-group row">
        <label class="col-md-2 control-label">Uploaded Evidence Info</label>
        <div class="col-md-3">
          <%= link_to "Download", @report.avatar.url(:original, false) unless @report.avatar.blank? %> 
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-8">
      <div class="form-group row">
        <label class="col-md-2 control-label">Status</label>
        <div class="col-md-8" style="font-weight:bolder;color:green">
          <%= @report.status %>  
        </div>
      </div>
    </div>
  </div>
 <div class="form-group">
    <div class="col-md-8">
      <div class="form-group row">
  <% if @report.status == 'Completed' && user_role=='Advisor' %>
         
            <%= link_to 'Submit', submit_report_report_path(:id=>@report.id), data: { confirm: 'Are you sure want to submit to director?' }, :class=>'btn btn-primary btn-xs' %>
          
        <% end %>
     </div>
      </div>
    </div>

    <% if @report.goals.present? %><br>
   
    <% @goals = @report.goals %>

    <table class="table table-stripped">
    <tr>
    <th>Outcome</th>
    <th>Learning goals</th>
    <th>Strategic plan</th>
    <th>Measures</th>
    <th>Performance Benchmark</th>
    <th>Data Results</th>
    <th>Data Analysis</th>
    <th>Recommendations</th>
    </tr>
    <% @goals.each do |g| %>
      <tr>
      <td><%= g.outcome %></td>
      <td><%= g.learning_goals %></td>
      <td><%= g.strategic_plan %></td>
      <td><%= g.measure_type %></td>
      <td><%= g.performance_benchmark %></td>
      <td><%= g.data_results %></td>
      <td><%= g.data_analysis %></td>
      <td><%= g.recommendations %></td>
      </tr>
    <% end %>
</table>
    <%else%>
     <p>No goals created</p>
    <%end%>

app/views/reports/submit_review.js.erb
window.location.reload();